version: "3.3"

services:
  app:
    build:
      args:
        PRODUCTION: 0
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      SUPERUSER_LOGIN: admin
      SUPERUSER_PASSWORD: "1234"
  db:
    ports:
      - "5432:5432"
