version: "3.3"

services:
  app:
    build:
      args:
        PRODUCTION: 1
  server:
    depends_on:
      - app
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/media
      - ./nginx/certbot/www:/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
