version: "3.8"

services:
  app:
    build:
      args:
        PRODUCTION: 1
  server:
    depends_on:
      - app
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
