version: "3.8"

services:
  app:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/photos
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: GCPwKXdha#4%
      POSTGRES_DB: 1september

volumes:
  postgres_data:
  static:
  media:
