# Generated by Django 3.1 on 2020-08-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('verified', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
